import "server-only";

import { Address, Networks, TransactionBuilder, rpc, xdr } from "@stellar/stellar-sdk";
import type { Result } from "@stellar/stellar-sdk/contract";

import { Client as MilestoneProofClient } from "@/lib/chain/bindings";
import { SOROBAN_RPC_URL, type StellarNetwork } from "@/lib/stellar";

/**
 * Server half of the wallet-signed anchoring flow.
 *
 * Signing happens in the browser, so a single server action cannot own the
 * whole transaction. It splits in three:
 *
 *   1. here, `buildUnsigned` — assemble and simulate, hand back base64 XDR;
 *   2. the browser — the wallet kit signs that string and nothing else;
 *   3. here, `submitSigned` — verify what came back, then submit and poll.
 *
 * Step 3 is the reason this file is careful. The signed XDR arrives from the
 * client, so it is untrusted input: `assertInvocation` re-derives what the
 * transaction is allowed to be and refuses anything else. Without that check a
 * user could sign any transaction they liked and have the server record it as
 * an anchor.
 *
 * `src/lib/chain/bindings.ts` is generated by
 * `stellar contract bindings typescript` from the deployed contract and is
 * ESLint-ignored. Regenerate it, never edit it — see contracts/README.md.
 */

export const NETWORK_PASSPHRASE: Record<StellarNetwork, string> = {
  testnet: Networks.TESTNET,
  mainnet: Networks.PUBLIC,
};

/** How long to keep polling `getTransaction` before giving up. */
const SUBMIT_TIMEOUT_MS = 30_000;
const POLL_INTERVAL_MS = 1_000;

export type ChainConfig = {
  contractId: string;
  network: StellarNetwork;
};

/** The contract this deployment anchors against, or null if unconfigured. */
export function chainConfig(): ChainConfig | null {
  const contractId = process.env.NEXT_PUBLIC_MILESTONE_PROOF_CONTRACT_ID?.trim();
  if (!contractId) return null;

  const network =
    process.env.NEXT_PUBLIC_STELLAR_NETWORK === "mainnet" ? "mainnet" : "testnet";
  return { contractId, network };
}

export function rpcServer(network: StellarNetwork): rpc.Server {
  return new rpc.Server(SOROBAN_RPC_URL[network]);
}

function contractClient(config: ChainConfig, publicKey: string): MilestoneProofClient {
  return new MilestoneProofClient({
    contractId: config.contractId,
    networkPassphrase: NETWORK_PASSPHRASE[config.network],
    rpcUrl: SOROBAN_RPC_URL[config.network],
    publicKey,
    allowHttp: false,
  });
}

/** Which contract function an anchor action invokes. */
export type ChainMethod =
  | "create_project_ref"
  | "submit_milestone_proof"
  | "approve_milestone"
  | "reject_milestone";

export type BuildRequest = {
  config: ChainConfig;
  /** The account that will sign. Becomes the transaction source. */
  signer: string;
  method: ChainMethod;
  args: Record<string, unknown>;
};

/**
 * Assemble and simulate, returning unsigned base64 XDR for the wallet.
 *
 * Simulation is what surfaces a contract error *before* the user is asked to
 * sign — an already-approved milestone or an unregistered project fails here,
 * costing nothing, rather than as a failed transaction they paid for.
 */
export async function buildUnsigned(request: BuildRequest): Promise<string> {
  const client = contractClient(request.config, request.signer);

  // The bindings expose one method per contract function, each taking a named
  // argument object. Indexing rather than switching keeps the four call sites
  // from drifting apart.
  const methods = client as unknown as Record<
    ChainMethod,
    (args: Record<string, unknown>) => Promise<AssembledWrite>
  >;

  const assembled = await methods[request.method](request.args);

  /*
   * A failed simulation has to be raised by hand.
   *
   * `AssembledTransaction.simulate()` does not throw when the contract rejects
   * the call — it only *assembles* on success, and otherwise leaves `built`
   * holding the raw transaction: no footprint, no resource fee. `toXDR()`
   * returns that quite happily, so without this check the flow carries on,
   * prompts for a signature, and the network refuses the transaction at
   * submission. The user then sees "the network rejected the transaction" for
   * what is really "this milestone is already approved".
   *
   * Simulating before signing is the whole point of the prepare step; this is
   * what makes it mean anything.
   */
  if (assembled.simulation && rpc.Api.isSimulationError(assembled.simulation)) {
    throw new Error(simulationFailure(assembled));
  }

  return assembled.toXDR();
}

/** The parts of the bindings' `AssembledTransaction` this module relies on. */
type AssembledWrite = {
  toXDR: () => string;
  simulation?: rpc.Api.SimulateTransactionResponse;
  result: Result<void>;
};

/**
 * Name what the contract actually objected to.
 *
 * Every write returns `Result<(), Error>`, so `result` decodes an
 * `Error(Contract, #5)` back into the contract's own name — "InvalidStatus" —
 * which `describe` in `actions.ts` turns into a sentence. Anything else is not
 * a contract error at all (a host failure, an unfunded source, expired state),
 * and there the raw simulation text is the only description available.
 */
function simulationFailure(assembled: AssembledWrite): string {
  try {
    const outcome = assembled.result;
    if (outcome.isErr()) return outcome.unwrapErr().message;
  } catch {
    // `result` rethrows when the failure has no contract error to decode.
  }

  return assembled.simulation && rpc.Api.isSimulationError(assembled.simulation)
    ? assembled.simulation.error
    : "The transaction could not be simulated.";
}

export type SubmitResult = {
  txHash: string;
  ledger: number | null;
  /** Source account of the submitted transaction — the address that signed. */
  signer: string;
};

/**
 * Reject a signed transaction that is not the one we prepared.
 *
 * The client is free to sign whatever it wants; it is not free to have the
 * server believe it. A transaction reaches the database only if it carries
 * exactly one operation, that operation invokes our contract, and it calls the
 * function we expect. Arguments are checked by the caller, which knows what it
 * asked for.
 */
function assertInvocation(
  envelopeXdr: string,
  config: ChainConfig,
  method: ChainMethod,
): { source: string } {
  const tx = TransactionBuilder.fromXDR(envelopeXdr, NETWORK_PASSPHRASE[config.network]);

  if ("innerTransaction" in tx) {
    throw new Error("Fee-bump transactions are not accepted here.");
  }
  if (tx.operations.length !== 1) {
    throw new Error("Expected exactly one operation in the signed transaction.");
  }

  const operation = tx.operations[0];
  if (operation.type !== "invokeHostFunction") {
    throw new Error(`Expected a contract invocation, got ${operation.type}.`);
  }

  const hostFunction = operation.func;
  if (hostFunction.switch() !== xdr.HostFunctionType.hostFunctionTypeInvokeContract()) {
    throw new Error("Expected a contract invocation.");
  }

  const invocation = hostFunction.invokeContract();
  const invokedContract = Address.fromScAddress(invocation.contractAddress()).toString();
  if (invokedContract !== config.contractId) {
    throw new Error("The signed transaction targets a different contract.");
  }

  const invokedMethod = invocation.functionName().toString();
  if (invokedMethod !== method) {
    throw new Error(`The signed transaction calls ${invokedMethod}, not ${method}.`);
  }

  return { source: tx.source };
}

/**
 * Verify, submit, and wait for the ledger to include it.
 *
 * Returns only once the transaction has actually succeeded. A `TRY_AGAIN_LATER`
 * or a timeout is an error here rather than an optimistic success, because the
 * caller is about to write a row asserting this happened.
 */
export async function submitSigned(
  envelopeXdr: string,
  config: ChainConfig,
  method: ChainMethod,
): Promise<SubmitResult> {
  const { source } = assertInvocation(envelopeXdr, config, method);

  const server = rpcServer(config.network);
  const transaction = TransactionBuilder.fromXDR(
    envelopeXdr,
    NETWORK_PASSPHRASE[config.network],
  );

  const sent = await server.sendTransaction(transaction);
  if (sent.status === "ERROR" || sent.status === "DUPLICATE") {
    throw new Error(`The network rejected the transaction (${sent.status}).`);
  }

  const deadline = Date.now() + SUBMIT_TIMEOUT_MS;
  while (Date.now() < deadline) {
    const result = await server.getTransaction(sent.hash);

    if (result.status === rpc.Api.GetTransactionStatus.SUCCESS) {
      return {
        txHash: sent.hash,
        ledger: result.ledger ?? null,
        signer: source,
      };
    }
    if (result.status === rpc.Api.GetTransactionStatus.FAILED) {
      throw new Error("The transaction failed on chain.");
    }

    await new Promise((resolve) => setTimeout(resolve, POLL_INTERVAL_MS));
  }

  throw new Error(
    `The transaction was submitted but not confirmed within ${SUBMIT_TIMEOUT_MS / 1000}s. ` +
      `Check ${sent.hash} on the explorer before retrying.`,
  );
}
